package iplanalyser;

public enum SortField {

    AVERAGE, FOURS, SIX, STRIKE_RATE, FourAndSix, RUNS, ECONOMY, SIX_FOUR, FIVE_FOUR, AVERAGE_STRIKE, RUNS_AVERAGE, WICKET_AVERAGE, BATTINGBOLLING_AVERAGE, BOLLING_AVERAGE, AVG_STRIKE, ALL_ROUNDER, WICKETS;
}
